### PR TITLE
support method to 23 so ledger can be used to safe the owner key.

### PR DESCRIPTION
**Pull request by wyx1987**
Add support to method 23.
Support to display params of map and text string.
Can be used to store the owner key and sign messages like ChangeOwnerAddress, WithdrawBalance.

### CODE REVIEW

**Comment by jleni** [comment]
Thanks for your contribution @wyx1987!

We are working on a redesign to extend support to a wider range of methods. 
The problem, at the moment, is that methods are linked to actor types. Transactions do not include this information so we cannot be certain about what methods are available, parameter types, etc.

We are looking at a long term solution for this. We will send you an update later this week about this.

**Comment by wyx1987** [comment]
> Thanks for your contribution @wyx1987!
> 
> We are working on a redesign to extend support to a wider range of methods.
> The problem, at the moment, is that methods are linked to actor types. Transactions do not include this information so we cannot be certain about what methods are available, parameter types, etc.
> 
> We are looking at a long term solution for this. We will send you an update later this week about this.

Hi @jleni , are there any updates you can share with me about the new version of the ledger app?

**Comment by Stebalien** [comment]
(filed https://github.com/Zondax/ledger-filecoin/issues/65 before I noticed this PR)

Ideally the device would display the method name/actor and the decoded parameters. However, in expert mode, there's really no reason not to allow arbitrary methods with arbitrary parameters. That's really the only long-term solution that will work in all cases.

**Comment by hyunmoon** [comment]
@jleni Could you tell us when this PR is going to be reviewed?

**Comment by hyunmoon** [comment]
I see that the new version is released but this PR is still pending review.
Is it going to be merged anytime soon? @jleni

**Comment by arajasek** [comment]
> Ideally the device would display the method name/actor and the decoded parameters. However, in expert mode, there's really no reason not to allow arbitrary methods with arbitrary parameters. That's really the only long-term solution that will work in all cases.

Yeah, I'd agree

**Comment by jleni** [comment]
Superseded by #74

**Pull request closed without merging**
